# Generated by Django 5.0.1 on 2024-02-06 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'event_table',
            },
        ),
        migrations.CreateModel(
            name='IngredientsModel',
            fields=[
                ('ingreds_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingreds_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ingredients_table',
            },
        ),
        migrations.CreateModel(
            name='MainCategoryModel',
            fields=[
                ('main_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'main_category_table',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('user_image', models.ImageField(upload_to='images/user_profile/')),
                ('user_password', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_create_date', models.DateTimeField(auto_now_add=True)),
                ('user_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
        migrations.CreateModel(
            name='RecipePostModel',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=100)),
                ('post_calorie', models.CharField(max_length=50)),
                ('post_time_needed', models.CharField(max_length=50)),
                ('post_nutrition_facts', models.CharField(max_length=100)),
                ('post_description', models.CharField(max_length=250)),
                ('post_procedure', models.CharField(max_length=350)),
                ('post_ingredients', models.CharField(max_length=250)),
                ('recipe_image', models.ImageField(upload_to='images/recipe_img/')),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.eventmodel')),
            ],
            options={
                'db_table': 'recipe_post_table',
            },
        ),
        migrations.CreateModel(
            name='PostIngredientsModel',
            fields=[
                ('post_ingreds_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_ingreds_name', models.CharField(max_length=100)),
                ('ingreds_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.ingredientsmodel')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.recipepostmodel')),
            ],
            options={
                'db_table': 'postingredients_table',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=100)),
                ('main_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.maincategorymodel')),
            ],
            options={
                'db_table': 'sub_category_table',
            },
        ),
        migrations.AddField(
            model_name='recipepostmodel',
            name='sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.subcategorymodel'),
        ),
        migrations.CreateModel(
            name='EventSubcategoryModel',
            fields=[
                ('event_subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.eventmodel')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.subcategorymodel')),
            ],
            options={
                'db_table': 'event_subcategory_table',
            },
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.recipepostmodel')),
            ],
            options={
                'db_table': 'tags_table',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('revw_id', models.AutoField(primary_key=True, serialize=False)),
                ('revw', models.CharField(max_length=100)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.recipepostmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel')),
            ],
            options={
                'db_table': 'review_table',
            },
        ),
        migrations.AddField(
            model_name='recipepostmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel'),
        ),
    ]
