# Generated by Django 5.0.1 on 2024-02-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_recipepostmodel_post_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubcategorymodel',
            name='event_subcategory_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipepostmodel',
            name='post_description',
            field=models.CharField(max_length=600),
        ),
    ]
