# Generated by Django 5.0.1 on 2024-02-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_eventsubcategorymodel_event_subcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepostmodel',
            name='post_ingredients',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='recipepostmodel',
            name='post_procedure',
            field=models.TextField(),
        ),
    ]
