# Generated by Django 5.0.1 on 2024-02-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_recipepostmodel_post_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepostmodel',
            name='post_ingredients',
            field=models.TextField(),
        ),
    ]
