# Generated by Django 5.0.1 on 2024-02-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_eventmodel_event_ima'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='event_ima',
            new_name='event_img',
        ),
    ]
