# Generated by Django 5.0.1 on 2024-02-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_rename_event_ima_eventmodel_event_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepostmodel',
            name='post_additional_notes_by_chef',
            field=models.TextField(null=True),
        ),
    ]
