# Generated by Django 5.0.1 on 2024-02-08 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_recipepostmodel_post_additional_notes_by_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepostmodel',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.eventmodel'),
        ),
    ]
