# Generated by Django 5.0.1 on 2024-02-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_alter_recipepostmodel_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepostmodel',
            name='post_additional_notes_by_chef',
            field=models.TextField(blank=True, null=True),
        ),
    ]
