# Generated by Django 5.0.1 on 2024-02-09 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_alter_recipepostmodel_post_additional_notes_by_chef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='post_id',
        ),
        migrations.CreateModel(
            name='RecipePostCommentModel',
            fields=[
                ('revw_id', models.AutoField(primary_key=True, serialize=False)),
                ('revw', models.CharField(max_length=100)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.recipepostmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel')),
            ],
            options={
                'db_table': 'comment_table',
            },
        ),
    ]
