# Generated by Django 5.0.1 on 2024-02-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_remove_reviewmodel_post_id_recipepostcommentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='revw',
            field=models.TextField(),
        ),
    ]
