# Generated by Django 5.0.1 on 2024-02-12 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_alter_recipepostmodel_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_image1', models.ImageField(upload_to='images/post_img/')),
                ('recipe_image2', models.ImageField(upload_to='images/post_img/')),
                ('recipe_image3', models.ImageField(upload_to='images/post_img/')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.recipepostmodel')),
            ],
            options={
                'db_table': 'recipe_images_table',
            },
        ),
    ]
