# Generated by Django 5.0.1 on 2024-02-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_recipeimagesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepostcommentmodel',
            name='revw',
        ),
        migrations.AddField(
            model_name='recipepostcommentmodel',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
