# Generated by Django 5.0.1 on 2024-02-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_remove_recipepostcommentmodel_revw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='username',
            new_name='user_name',
        ),
    ]
