# Generated by Django 5.0.1 on 2024-02-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0018_remove_recipepostmodel_post_procedure_procedurestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurestep',
            name='step_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
