# Generated by Django 5.0.1 on 2024-02-28 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0020_remove_procedurestep_step_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('fat', models.FloatField(blank=True)),
                ('sugar', models.CharField(blank=True, max_length=100)),
                ('sodium', models.CharField(blank=True, max_length=100)),
                ('carbohydrates', models.FloatField(blank=True)),
                ('fiber', models.FloatField(blank=True)),
                ('protein', models.FloatField(blank=True)),
            ],
            options={
                'db_table': 'nutrition_facts_table',
            },
        ),
        migrations.RemoveField(
            model_name='recipepostmodel',
            name='post_calorie',
        ),
        migrations.RemoveField(
            model_name='recipepostmodel',
            name='post_nutrition_facts',
        ),
        migrations.AddField(
            model_name='recipepostmodel',
            name='nutrition_facts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.nutritionfact'),
        ),
    ]
