# Generated by Django 5.0.1 on 2024-02-28 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0021_nutritionfact_remove_recipepostmodel_post_calorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepostmodel',
            name='nutrition_facts',
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.recipepostmodel'),
        ),
    ]
