# Generated by Django 5.0.1 on 2024-02-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0022_remove_recipepostmodel_nutrition_facts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionfact',
            name='fat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
