# Generated by Django 5.0.1 on 2024-02-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0024_alter_nutritionfact_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionfact',
            name='servings_per_batch',
            field=models.IntegerField(null=True),
        ),
    ]
