# Generated by Django 5.0.1 on 2024-02-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0025_nutritionfact_servings_per_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritionfact',
            old_name='carbohydrates',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='nutritionfact',
            old_name='fat',
            new_name='Value',
        ),
        migrations.RemoveField(
            model_name='nutritionfact',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='nutritionfact',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='nutritionfact',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='nutritionfact',
            name='servings_per_batch',
        ),
        migrations.RemoveField(
            model_name='nutritionfact',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='nutritionfact',
            name='sugar',
        ),
    ]
