# Generated by Django 5.0.1 on 2024-02-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0026_rename_carbohydrates_nutritionfact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepostmodel',
            name='post_calories',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
