# Generated by Django 5.0.1 on 2024-02-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0027_recipepostmodel_post_calories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postingredientsmodel',
            old_name='ingreds_id',
            new_name='ingredient_name',
        ),
        migrations.RenameField(
            model_name='postingredientsmodel',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='postingredientsmodel',
            name='post_ingreds_name',
        ),
        migrations.RemoveField(
            model_name='recipepostmodel',
            name='post_ingredients',
        ),
        migrations.AddField(
            model_name='postingredientsmodel',
            name='post_ingredient_detail',
            field=models.TextField(null=True),
        ),
    ]
