# Generated by Django 5.0.1 on 2024-02-28 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0029_alter_postingredientsmodel_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingredientsmodel',
            name='ingredient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.ingredientsmodel'),
        ),
    ]
