# Generated by Django 5.0.1 on 2024-02-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0032_savedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
