# Generated by Django 5.0.1 on 2024-03-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0034_recipepostviewmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipePostViewModel',
        ),
    ]
