# Generated by Django 5.0.1 on 2024-03-04 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0035_delete_recipepostviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postingredientsmodel',
            name='ingredient_name',
        ),
        migrations.DeleteModel(
            name='IngredientsModel',
        ),
    ]
