# Generated by Django 5.0.1 on 2024-03-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0036_remove_postingredientsmodel_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipepostmodel',
            old_name='post_time_needed',
            new_name='post_difficulty',
        ),
    ]
