# Generated by Django 5.0.1 on 2024-03-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0037_rename_post_time_needed_recipepostmodel_post_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipepostmodel',
            old_name='post_difficulty',
            new_name='post_time_needed',
        ),
    ]
