# Generated by Django 5.0.1 on 2024-03-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0038_rename_post_difficulty_recipepostmodel_post_time_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepostmodel',
            name='post_difficulty_level',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
