# Generated by Django 5.0.1 on 2024-03-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0043_alter_usermodel_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postingredientsmodel',
            name='ingredients_for',
        ),
    ]
