# Generated by Django 5.0.1 on 2024-03-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0047_rename_recipe_image1_recipeimagesmodel_final_result_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipepostcommentmodel',
            old_name='review',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='recipepostcommentmodel',
            old_name='revw_id',
            new_name='comment_id',
        ),
    ]
