# Generated by Django 5.0.1 on 2024-03-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0048_rename_review_recipepostcommentmodel_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='revw',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='revw_id',
            new_name='review_id',
        ),
    ]
