# Generated by Django 5.0.1 on 2024-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0049_rename_revw_reviewmodel_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='review_overall',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
