# Generated by Django 5.0.1 on 2024-04-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0050_reviewmodel_review_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepostmodel',
            name='is_archived',
            field=models.BooleanField(choices=[(True, 'Archived'), (False, 'Not Archived')], default=False),
        ),
    ]
