# Generated by Django 5.0.1 on 2024-04-07 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0051_recipepostmodel_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepostmodel',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='recipepostmodel',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
