# Generated by Django 5.0.1 on 2024-04-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0052_remove_recipepostmodel_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepostmodel',
            name='is_archived',
            field=models.BooleanField(choices=[(True, 'Archived'), (False, 'Not Archived')], default=False),
        ),
    ]
